test: off

branches:
  except:
  - /travis/

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  GYP_MSVS_VERSION: 2019
  PDFium_BRANCH: $(APPVEYOR_REPO_TAG_NAME)
  matrix:
    - PDFium_V8: enabled
    - PDFium_V8: disabled

configuration:
  - Release

platform:
  - x86
  - x64

build_script:
  - call build.bat
  - cd %APPVEYOR_BUILD_FOLDER%
  - call test.bat

artifacts:
  - path: pdfium-*.zip
    name: PDFium library

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: "This version was built with branch $(APPVEYOR_REPO_TAG_NAME) of PDFium"
    force_update: true
    auth_token:
      secure: JH8IVbdgVLz16ZXQLO41jQ5OsC7wR8IMRPAzinrdqpvgfhe/btgtr1xZ5trO2Eux
    on:
      appveyor_repo_tag: true
