on:
  workflow_call:
    inputs:
      artifact_x64:
        description: Artifact containing the x64 version
        type: string
        required: true
      artifact_arm64:
        description: Artifact containing the arm64 version
        type: string
        required: true
    outputs:
      artifact:
        description: "The name of the artifact"
        value: ${{ jobs.build.outputs.artifact }}

jobs:
  build:
    runs-on: macos-latest
    outputs:
      artifact: ${{ steps.init.outputs.artifact }}
    env:
      ARTIFACT_X64: ${{ inputs.artifact_x64 }}
      ARTIFACT_ARM64: ${{ inputs.artifact_arm64 }}
    steps:
      - name: Initialize
        id: init
        run: |
          echo "artifact=$ARTIFACT_X64" | sed "s/x64/univ/g" >> $GITHUB_OUTPUT
      - name: Download ${{ inputs.artifact_x64 }}
        uses: actions/download-artifact@v7
        with:
          name: ${{ inputs.artifact_x64 }}
          path: ${{ inputs.artifact_x64 }}
      - name: Download ${{ inputs.artifact_arm64 }}
        uses: actions/download-artifact@v7
        with:
          name: ${{ inputs.artifact_arm64 }}
          path: ${{ inputs.artifact_arm64 }}
      - name: Create universal library
        run: |
          cp -r $ARTIFACT_ARM64 $OUTPUT_DIR
          sed -i '' '/target_cpu/d' $OUTPUT_DIR/args.gn
          rm $OUTPUT_DIR/lib/libpdfium.dylib
          lipo -create \
            $ARTIFACT_ARM64/lib/libpdfium.dylib \
            $ARTIFACT_X64/lib/libpdfium.dylib \
            -output $OUTPUT_DIR/lib/libpdfium.dylib
        env:
          OUTPUT_DIR: ${{ steps.init.outputs.artifact }}

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ steps.init.outputs.artifact }}
          path: ${{ steps.init.outputs.artifact }}
